## This is a proposed format for declaring GitHub apps.
##
## TODO: move this file to the probot/template repo


## Metadata - these will also be inferred from package.json
name: my-sweet-probot-app
description: It's so sweet
url: https://example.com
public: true

## These are the permissions granted to the app.
## `access` can be `read`, `write`, or `none`
## See https://developer.github.com/webhooks/#events for more about events
permissions:
  ## Repository permissions

  # administration:
  #   access: read
  # contents:
  #   access: read
  #   events:
  #     - commit_comment
  #     - create
  #     - delete
  #     - fork
  #     - gollum
  #     - push
  #     - release
  # deployments:
  #   access: read
  #   events:
  #     - deployment
  #     - deployment_status
  # issues:
  #   access: read
  #   events:
  #     - issue_comment
  #     - issues
  #     - milestone
  # metadata:
  #   access: read
  #   events:
  #     - label
  #     - public
  #     - repository
  #     - watch
  # pages:
  #   access: read
  #   events:
  #     - page_build
  # pull_requests:
  #   access: read
  #   events:
  #     - milestone
  #     - pull_request
  #     - pull_request_review
  #     - pull_request_review_comment
  # repository_hooks:
  #   access: read
  # repository_projects:
  #   access: read
  #   events:
  #     - project_card
  #     - project_column
  #     - project
  # single_file:
  #   access: read
  #   path: .github/config.yml
  # statuses:
  #   access: read
  #   events:
  #     - status

  ## Organization permissions
  # members:
  #   access: read
  #   events:
  #     - member
  #     - membership
  #     - organization
  #     - team
  #     - team_add
  # organization_projects:
  #   access: read
  #   events:
  #     - project_card
  #     - project_column
  #     - project
  # team_discussions:
  #   access: read

# These settings will all be automatically set at runtime

# callback_url: /path/to/auth
# setup_url: /path/to/setup
# webhook_url: /path/to/webhook
# webhook_secret: asdf1234
